#!/bin/bash
#
# Script by Phr34kz
# Add more lines below if any fixes or addons are available
#
SOURCE="${BASH_SOURCE[0]}"

echo -n "\n\nDo you want to remove your previous install? Y for Yes. N for No: "
read remove1

if [[ $remove1 =~ [yY](es)* ]]; then
	# Remove Previous Packages
	rm -rf pybombs
	rm -rf gnuradio
else
	echo -en "Not removing\n\n"
fi

clear
echo -n "\n\nDo you want clone pybombs and copy all fixes? Y for Yes. N for No: "
read cloning

if [[ $cloning =~ [yY](es)* ]]; then
	# Make and clone
	mkdir gnuradio
	git clone git://github.com/pybombs/pybombs

	# wait for 3 Seconds
	sleep 3

	# Copy recipe fixes
	cp $SOURCE/recipe-fix/armadillo.lwr /pybombs/recipes/armadillo.lwr
	cp $SOURCE/recipe-fix/boost.lwr /pybombs/recipes/boost.lwr
	cp $SOURCE/recipe-fix/gnuradio.lwr /pybombs/recipes/gnuradio.lwr
	cp $SOURCE/recipe-fix/swig.lwr /pybombs/recipes/swig.lwr
	cp $SOURCE/recipe-fix/uhd.lwr /pybombs/recipes/uhd.lwr
	cp $SOURCE/recipe-fix/cmake.lwr /pybombs/recipes/cmake.lwr
	cp $SOURCE/recipe-fix/gqrx.lwr /pybombs/recipes/gqrx.lwr
	#cp /recipe-fix/gr-smartnet.lwr /pybombs/recipes/gr-smartnet.lwr

	# Copy Addons
	cp $SOURCE/recipe-fix/pysstv.lwr /pybombs/recipes/pysstv.lwr
	cp $SOURCE/recipe-fix/slowrx.lwr /pybombs/recipes/slowrx.lwr

	# Copy startup script
	cp $SOURCE/install.sh /pybombs/install.sh

	# Copy templates
	cp $SOURCE/templates-fix/cmake.lwt /pybombs/templates/cmake.lwt
	cp $SOURCE/templates-fix/autoconf.lwt /pybombs/templates/autoconf.lwt
else
	echo -en "Not cloning\n\n"
fi

sleep 5
